// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurismoArrieriasV2.Datos;

namespace TurismoArrieriasV2.Migrations
{
    [DbContext(typeof(AplicationDBcontext))]
    partial class AplicationDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TurismoArrieriasV2.Models.imagensitio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("sitioid")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("sitioid");

                    b.ToTable("ImagenSitio");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.preferencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prioridad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Preferencia");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.ruta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("costo")
                        .HasColumnType("int");

                    b.Property<int>("distancia")
                        .HasColumnType("int");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Ruta");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.sitio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("caracteristicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("posicionX")
                        .HasColumnType("int");

                    b.Property<int>("posicionY")
                        .HasColumnType("int");

                    b.Property<int?>("rutaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rutaid");

                    b.ToTable("Sitio");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lugarResidencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("preferencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.imagensitio", b =>
                {
                    b.HasOne("TurismoArrieriasV2.Models.sitio", "sitio")
                        .WithMany("galeria")
                        .HasForeignKey("sitioid");

                    b.Navigation("sitio");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.sitio", b =>
                {
                    b.HasOne("TurismoArrieriasV2.Models.ruta", null)
                        .WithMany("puntosConexion")
                        .HasForeignKey("rutaid");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.ruta", b =>
                {
                    b.Navigation("puntosConexion");
                });

            modelBuilder.Entity("TurismoArrieriasV2.Models.sitio", b =>
                {
                    b.Navigation("galeria");
                });
#pragma warning restore 612, 618
        }
    }
}
